"""Port used by business services; SQL remains in storage adapters."""
from typing import Protocol, ContextManager

class Repository(Protocol):
    def atomic(self) -> ContextManager: ...
    def one(self, table: str, identity: str) -> dict | None: ...
    def insert(self, table: str, values: dict) -> None: ...
    def update(self, table: str, identity: str, values: dict) -> None: ...
    def context(self) -> dict | None: ...
    def receipt(self, request_id: str) -> dict | None: ...
    def members(self, query: str, limit: int, offset: int) -> list: ...
    def cards(self, member_id: str) -> list: ...
    def card_types(self) -> list: ...
    def ledger(self, member_id: str, limit: int, offset: int) -> list: ...
    def refunded(self, source_id: str) -> dict: ...
    def audit(self) -> dict: ...
    def events(self, limit: int) -> list: ...
