(function(){'use strict';
var token=sessionStorage.getItem('liteshop-user-token')||'',dash=document.getElementById('dashboard'),loggedOut=document.getElementById('logged-out'),status=document.getElementById('status'),state=null;
function esc(v){return String(v==null?'':v).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function headers(){return {'Authorization':'Bearer '+token}}
function msg(v){status.textContent=v;var local=document.getElementById('page-message');if(local){local.textContent=v;local.className='inline-message error-message'}}
function panelMsg(id,v,error){var node=document.getElementById(id);if(node){node.textContent=v||'';node.className='inline-message '+(error?'error-message':'success-message')}}
function call(path,opt){opt=opt||{};opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});return fetch(path,opt).then(function(r){return r.json().then(function(x){if(!r.ok||!x.ok)throw new Error(x.error&&x.error.message||'请求失败');return x})})}
function renderMetrics(metrics){metrics=metrics||{};var items=[['member_count','会员数量'],['new_member_count','近30天新增会员'],['transaction_count','交易笔数'],['consume_amount','消费金额（分）'],['recharge_amount','储值金额（分）']];document.getElementById('metrics').innerHTML=items.map(function(x){return '<div class="metric-card"><strong>'+esc(metrics[x[0]]||0)+'</strong><span>'+x[1]+'</span></div>'}).join('')}
function render(data){state=data;dash.hidden=false;loggedOut.hidden=true;document.getElementById('welcome').textContent='您好，'+data.user.username+'（'+data.user.email+'）';renderMetrics(data.metrics);var shops=data.shops||[],terms=data.terminals||[];document.getElementById('shops').innerHTML=shops.length?shops.map(function(s){return '<p><b>'+esc(s.name||s.shop_id)+'</b> · '+esc(s.member_count)+' 位会员 · '+esc(s.card_count)+' 张卡 · '+esc(s.transaction_count)+' 笔交易</p>'}).join(''):'<p class="muted">尚未绑定终端</p>';document.getElementById('terminals').innerHTML=terms.length?'<h3>终端</h3>'+terms.map(function(t){return '<p>'+esc(t.serial_no||'未上报')+' · '+esc(t.device_id)+' · '+esc(t.status)+'</p>'}).join(''):'';var sel=document.getElementById('shop-select'),csel=document.getElementById('campaign-shop');sel.innerHTML='<option value="">全部已绑定门店</option>';csel.innerHTML='';shops.forEach(function(s){var o=document.createElement('option');o.value=s.shop_id;o.textContent=s.name||s.shop_id;sel.appendChild(o);csel.appendChild(o.cloneNode(true))});document.getElementById('services').innerHTML=shops.length?['MINIAPP_NOTICE','MINIAPP_QUERY','MINIAPP_APPOINTMENT','WECHAT_NOTICE','WECHAT_BROADCAST'].map(function(code){return '<button class="service" data-code="'+code+'">申请 '+code+'</button>'}).join(''):'<p class="muted">绑定终端后可申请</p>';Array.prototype.forEach.call(document.querySelectorAll('.service'),function(b){b.onclick=function(){var shop=sel.value||(shops[0]&&shops[0].shop_id);if(!shop)return msg('请先选择门店');call('/api/v1/account/services',{method:'POST',headers:headers(),body:JSON.stringify({shop_id:shop,service_code:b.dataset.code})}).then(function(){panelMsg('services-message','已提交 '+b.dataset.code+' 开通申请',false)}).catch(function(e){panelMsg('services-message',e.message,true)})}});loadMembers()}
function load(){if(!token){dash.hidden=true;loggedOut.hidden=false;msg('请先登录');return}call('/api/v1/account',{headers:headers()}).then(function(r){render(r.data);msg('已登录')}).catch(function(e){sessionStorage.removeItem('liteshop-user-token');token='';dash.hidden=true;loggedOut.hidden=false;msg(e.message)})}
document.getElementById('load-members').onclick=function(){loadMembers()};function loadMembers(){if(!token)return;var shop=document.getElementById('shop-select').value;panelMsg('members-message','正在查询…',false);call('/api/v1/account/members'+(shop?'?shop_id='+encodeURIComponent(shop):''),{headers:headers()}).then(function(r){var rows=Array.isArray(r.data)?r.data:[];document.getElementById('members').innerHTML=rows.length?'<table><tr><th>店铺</th><th>姓名</th><th>手机号</th><th>会员号</th></tr>'+rows.map(function(m){return '<tr><td>'+esc(m.shop_id)+'</td><td>'+esc(m.name)+'</td><td>'+esc(m.phone)+'</td><td>'+esc(m.member_no)+'</td></tr>'}).join('')+'</table>':'<p class="muted">暂无会员数据</p>';panelMsg('members-message','查询完成，共 '+rows.length+' 条记录',false)}).catch(function(e){panelMsg('members-message',e.message,true)})}
document.getElementById('campaign').onsubmit=function(e){e.preventDefault();panelMsg('campaign-message','正在创建群发任务…',false);call('/api/v1/account/message-campaigns',{method:'POST',headers:headers(),body:JSON.stringify({shop_id:document.getElementById('campaign-shop').value,channel:document.getElementById('campaign-channel').value,content:document.getElementById('campaign-content').value})}).then(function(r){panelMsg('campaign-message','群发任务已创建，目标关注者 '+r.data.target_count+' 人',false)}).catch(function(e){panelMsg('campaign-message',e.message,true)})};load()})();
